# Generated by Django 3.0.4 on 2020-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
