# Generated by Django 3.0.4 on 2020-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questions_questionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
