# Generated by Django 3.0.4 on 2020-12-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questions_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='no_of_attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
