# Generated by Django 3.0.4 on 2020-12-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201207_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='crctans',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_question',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='youranswer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
