# Generated by Django 3.1.4 on 2020-12-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201223_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='mark',
        ),
    ]
